#!/usr/bin/env node
/**
 * Derive the "Verified codebase counts" table in prompts/00-index.md.
 *
 * That table is the prompt library's shared fact base — every prompt is told to
 * trust it when prompts disagree. It has been hand-transcribed since the
 * library was created, and it has drifted at every refresh: route/controller
 * counts, migration counts, test counts, and workflow counts have all been
 * wrong at some point, and a wrong number there propagates into every doc the
 * prompts generate. Transcription is the defect; deriving removes the category.
 *
 * Modes:
 *   node scripts/check-counts.mjs            verify the table matches the repo
 *                                            (exit 1 on drift) — this is CI
 *   node scripts/check-counts.mjs --write    rewrite the table in place
 *
 * The table lives between the HTML markers below so the surrounding prose stays
 * hand-written. Anything descriptive that cannot be derived (why the upload
 * controllers live in a subdir, what a rate limiter is for) belongs in the
 * generated text HERE, not in the markdown — otherwise it is lost on rewrite.
 */

import { readFileSync, writeFileSync, readdirSync, existsSync, statSync } from 'node:fs';
import { join, dirname, resolve, basename } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const INDEX = join(ROOT, 'prompts', '00-index.md');
const BEGIN = '<!-- BEGIN:codebase-counts (generated by scripts/check-counts.mjs — do not edit by hand) -->';
const END = '<!-- END:codebase-counts -->';
const WRITE = process.argv.includes('--write');

// ---------------------------------------------------------------------------
// primitives
// ---------------------------------------------------------------------------

const isTest = (f) => /\.test\.(ts|tsx)$/.test(f);
const read = (p) => readFileSync(join(ROOT, p), 'utf8');

function ls(dir, { ext = null, includeTests = false, dirsOnly = false } = {}) {
  const full = join(ROOT, dir);
  if (!existsSync(full)) return [];
  return readdirSync(full)
    .filter((f) => {
      const st = statSync(join(full, f));
      if (dirsOnly) return st.isDirectory();
      if (!st.isFile()) return false;
      if (!includeTests && isTest(f)) return false;
      return ext ? f.endsWith(ext) : true;
    })
    .sort();
}

function walkFiles(dir, pred) {
  const out = [];
  const full = join(ROOT, dir);
  if (!existsSync(full)) return out;
  const rec = (d) => {
    for (const name of readdirSync(d)) {
      const p = join(d, name);
      const st = statSync(p);
      if (st.isDirectory()) rec(p);
      else if (pred(name, p)) out.push(p);
    }
  };
  rec(full);
  return out;
}

const fmtList = (xs) => xs.map((x) => `\`${x}\``).join(', ');

// ---------------------------------------------------------------------------
// metrics
// ---------------------------------------------------------------------------

const m = {};

// -- backend structure -------------------------------------------------------
m.routeFiles = ls('backend/src/routes', { ext: '.ts' });

const ctrlAll = ls('backend/src/controllers', { ext: '.ts' });
m.controllersDomain = ctrlAll.filter((f) => !['index.ts', 'testHelpers.ts'].includes(f));
m.uploadControllers = ls('backend/src/controllers/upload', { ext: '.ts' });

m.servicesTop = ls('backend/src/services', { ext: '.ts' });
m.serviceSubdirs = ls('backend/src/services', { dirsOnly: true }).map((d) => ({
  name: d,
  count: ls(`backend/src/services/${d}`, { ext: '.ts' }).length,
}));

const mwAll = ls('backend/src/middleware', { ext: '.ts' });
m.middleware = mwAll.filter((f) => f !== 'index.ts').map((f) => f.replace('.ts', ''));

// -- guards ------------------------------------------------------------------
m.rateLimiters = [...read('backend/src/middleware/rateLimiter.ts')
  .matchAll(/^export const (\w+) = rateLimit\(/gm)].map((x) => x[1]);

// `aiSpendGuard,` used as middleware in a route chain — the import line is
// `import { aiSpendGuard }` so it is excluded by requiring a trailing comma at
// end-of-line.
const spendFiles = [];
let spendMounts = 0;
for (const f of m.routeFiles) {
  const hits = [...read(`backend/src/routes/${f}`).matchAll(/^\s*aiSpendGuard,\s*$/gm)].length;
  if (hits) {
    spendMounts += hits;
    spendFiles.push(f.replace('.ts', ''));
  }
}
m.aiSpendGuard = { mounts: spendMounts, files: spendFiles };

m.storageBackends = ls('backend/src/services/storage', { ext: 'Backend.ts' })
  .map((f) => f.replace('Backend.ts', ''));

// -- data model --------------------------------------------------------------
const schema = read('backend/prisma/schema.prisma');
m.prismaModels = [...schema.matchAll(/^model (\w+) \{/gm)].length;

const migDirs = ls('backend/prisma/migrations', { dirsOnly: true });
m.migrations = { count: migDirs.length, newest: migDirs[migDirs.length - 1] };

const enc = read('backend/src/services/encryption.ts');
const phiBlock = enc.slice(
  enc.indexOf('export const PHI_FIELDS'),
  enc.indexOf('} as const', enc.indexOf('export const PHI_FIELDS'))
);
m.phi = {
  models: [...phiBlock.matchAll(/^ {2}(\w+): \[/gm)].length,
  fields: [...phiBlock.matchAll(/^\s+'(\w+Encrypted)',/gm)].length,
};
m.schemaEncryptedCols = [...schema.matchAll(/^\s+(\w+Encrypted)\s+String/gm)].length;

// -- frontend ----------------------------------------------------------------
m.frontendApi = ls('src/services/api', { ext: '.ts' });
const tsx = walkFiles('src/components', (n) => n.endsWith('.tsx') && !isTest(n));
m.frontendTsx = tsx.length;
m.frontendDirs = ls('src/components', { dirsOnly: true });
m.frontendHooks = ls('src/hooks', { ext: '.ts' });

// -- tests + CI --------------------------------------------------------------
m.backendTests = walkFiles('backend/src', (n) => isTest(n)).length;
m.frontendTests = walkFiles('src', (n) => isTest(n)).length;
m.workflows = ls('.github/workflows', { ext: '.yml' }).map((f) => f);
// Job ids are the 2-space keys under the top-level `jobs:` block. Scoped to
// that block because `on:` and `env:` also carry 2-space keys, and matched with
// `\s*$` rather than `\n` because the file may have CRLF line endings.
const ciYml = read('.github/workflows/ci.yml');
const jobsIdx = ciYml.search(/^jobs:\s*$/m);
const afterJobs = jobsIdx === -1 ? '' : ciYml.slice(jobsIdx);
m.ciJobs = [...afterJobs.matchAll(/^ {2}([a-z][\w-]*):\s*$/gm)].map((x) => x[1]);
if (m.ciJobs.length === 0) {
  console.error('✗ Parsed 0 CI jobs from ci.yml — the parser is broken, not the file.');
  process.exit(2);
}
m.e2eSpecs = ls('e2e', { ext: '.spec.ts' }).map((f) => f.replace('.spec.ts', ''));

// ---------------------------------------------------------------------------
// render
// ---------------------------------------------------------------------------

const subdirText = m.serviceSubdirs.map((d) => `\`${d.name}/\` (${d.count})`).join(', ');
const phiLock = m.phi.fields === m.schemaEncryptedCols
  ? `in lockstep with the schema's ${m.schemaEncryptedCols} \`*Encrypted\` columns`
  : `**MISMATCH: schema has ${m.schemaEncryptedCols} \`*Encrypted\` columns** — see \`phiFieldsCoverage.test.ts\``;

const rows = [
  ['Route files', `${m.routeFiles.length} (incl. \`index.ts\`)`, '`backend/src/routes/`'],
  ['Controllers',
   `${m.controllersDomain.length} domain controllers (+ \`index.ts\`, \`testHelpers.ts\`); upload logic lives in \`controllers/upload/\` (${m.uploadControllers.length} files)`,
   '`backend/src/controllers/`'],
  ['Services', `${m.servicesTop.length} top-level \`.ts\` (incl. \`index.ts\`) plus subdirs ${subdirText}`, '`backend/src/services/`'],
  ['Middleware', `${m.middleware.length} (+ \`index.ts\`): ${fmtList(m.middleware)}`, '`backend/src/middleware/`'],
  ['Rate limiters', `**${m.rateLimiters.length}** — ${fmtList(m.rateLimiters.map((r) => r.replace('Limiter', '')))}`, '`backend/src/middleware/rateLimiter.ts`'],
  ['`aiSpendGuard` mount points', `**${m.aiSpendGuard.mounts}** across ${m.aiSpendGuard.files.length} route files (${fmtList(m.aiSpendGuard.files)})`, '`backend/src/middleware/aiSpendGuard.ts`'],
  ['Storage backends', `**${m.storageBackends.length}** — ${fmtList(m.storageBackends)}; selected by \`STORAGE_BACKEND\`, \`local\` refused in prod/staging`, '`backend/src/services/storageService.ts`'],
  ['Frontend API modules', `${m.frontendApi.length - 1} + \`index.ts\``, '`src/services/api/`'],
  ['Frontend `.tsx` files', `**${m.frontendTsx}** across **${m.frontendDirs.length}** component dirs`, '`src/components/`'],
  ['Frontend hooks', `${m.frontendHooks.length - 1} + \`index.ts\``, '`src/hooks/`'],
  ['Prisma models', `${m.prismaModels}`, '`backend/prisma/schema.prisma`'],
  ['Prisma migrations', `**${m.migrations.count}** directories (newest \`${m.migrations.newest}\`)`, '`backend/prisma/migrations/`'],
  ['Encrypted PHI', `\`PHI_FIELDS\` = ${m.phi.models} models / ${m.phi.fields} fields, ${phiLock}`, '`backend/src/services/encryption.ts`'],
  ['Backend test files', `**${m.backendTests}** \`*.test.ts\``, '`backend/src/`'],
  ['Frontend test files', `**${m.frontendTests}**`, '`src/`'],
  ['GitHub workflows', `**${m.workflows.length}** — ${fmtList(m.workflows)}`, '`.github/workflows/`'],
  ['CI jobs in `ci.yml`', `**${m.ciJobs.length}** — ${fmtList(m.ciJobs)}`, '`.github/workflows/ci.yml`'],
  ['Playwright e2e specs', `**${m.e2eSpecs.length}** — ${fmtList(m.e2eSpecs)}`, '`e2e/`'],
];

const table = [
  BEGIN,
  '',
  '| Thing | Count | Path |',
  '|---|---|---|',
  ...rows.map(([a, b, c]) => `| ${a} | ${b} | ${c} |`),
  '',
  END,
].join('\n');

// ---------------------------------------------------------------------------
// apply / verify
// ---------------------------------------------------------------------------

const src = readFileSync(INDEX, 'utf8');
const b = src.indexOf(BEGIN);
const e = src.indexOf(END);

if (b === -1 || e === -1) {
  if (!WRITE) {
    console.error(
      `✗ ${basename(INDEX)} has no generated-counts block.\n` +
        `  Run: node scripts/check-counts.mjs --write`
    );
    process.exit(1);
  }
  console.error(`✗ Markers not found in ${basename(INDEX)}; insert them manually first.`);
  process.exit(1);
}

const current = src.slice(b, e + END.length);

if (WRITE) {
  writeFileSync(INDEX, src.slice(0, b) + table + src.slice(e + END.length), 'utf8');
  console.log(current === table ? '= counts table already current.' : '✓ counts table rewritten.');
  process.exit(0);
}

if (current === table) {
  console.log(`✓ prompts/00-index.md counts match the repo (${rows.length} metrics).`);
  process.exit(0);
}

console.error('✗ prompts/00-index.md counts have drifted from the repo.\n');
const cur = current.split('\n');
const want = table.split('\n');
for (let i = 0; i < Math.max(cur.length, want.length); i++) {
  if (cur[i] !== want[i]) {
    if (cur[i] !== undefined) console.error(`  - ${cur[i]}`);
    if (want[i] !== undefined) console.error(`  + ${want[i]}`);
  }
}
console.error('\nFix with: node scripts/check-counts.mjs --write');
process.exit(1);
